name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build . --file Docker/Dockerfile --tag amazon-clone:latest

    - name: Save image
      run: docker save amazon-clone:latest -o amazon-clone.tar

    - name: Upload image artifact
      uses: actions/upload-artifact@v4
      with:
        name: amazon-image
        path: amazon-clone.tar


  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: amazon-image

    - name: Load image
      run: docker load -i amazon-clone.tar

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag image
      run: docker tag amazon-clone:latest ${{ secrets.DOCKER_USERNAME }}/amazon-clone:latest

    - name: Push image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/amazon-clone:latest
      
